"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-05 01:11:04.035771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_api_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('google_name', sa.String(), nullable=True),
    sa.Column('google_picture', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_table('mediaprojectmapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_media_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_local_media_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_media_id', 'project_id', name='uq_media_project_mapping')
    )
    op.create_index(op.f('ix_mediaprojectmapping_original_media_id'), 'mediaprojectmapping', ['original_media_id'], unique=False)
    op.create_index(op.f('ix_mediaprojectmapping_project_id'), 'mediaprojectmapping', ['project_id'], unique=False)
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_account_id'), 'board', ['account_id'], unique=False)
    op.create_table('devicetoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicetoken_account_id'), 'devicetoken', ['account_id'], unique=False)
    op.create_index(op.f('ix_devicetoken_token_hash'), 'devicetoken', ['token_hash'], unique=False)
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_account_id'), 'refreshtoken', ['account_id'], unique=False)
    op.create_index(op.f('ix_refreshtoken_token_hash'), 'refreshtoken', ['token_hash'], unique=False)
    op.create_table('boardflowproject',
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('flow_project_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('board_id')
    )
    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('mentions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_board_id'), 'chatmessage', ['board_id'], unique=False)
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('short_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('w', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_account_id'), 'node', ['account_id'], unique=False)
    op.create_index(op.f('ix_node_board_id'), 'node', ['board_id'], unique=False)
    op.create_index(op.f('ix_node_short_id'), 'node', ['short_id'], unique=False)
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_board_id'), 'plan', ['board_id'], unique=False)
    op.create_table('reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ai_brief', sa.String(), nullable=True),
    sa.Column('aspect_ratio', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('source_board_id', sa.Integer(), nullable=True),
    sa.Column('source_node_short_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_board_id'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_media_id'), 'reference', ['media_id'], unique=True)
    op.create_index(op.f('ix_reference_source_board_id'), 'reference', ['source_board_id'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('uuid_media_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('local_path', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_account_id'), 'asset', ['account_id'], unique=False)
    op.create_index(op.f('ix_asset_node_id'), 'asset', ['node_id'], unique=False)
    op.create_index(op.f('ix_asset_uuid_media_id'), 'asset', ['uuid_media_id'], unique=True)
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source_variant_idx', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_board_id'), 'edge', ['board_id'], unique=False)
    op.create_table('pipelinerun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelinerun_plan_id'), 'pipelinerun', ['plan_id'], unique=False)
    op.create_table('planrevision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('rev_no', sa.Integer(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=True),
    sa.Column('edits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planrevision_plan_id'), 'planrevision', ['plan_id'], unique=False)
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_account_id'), 'request', ['account_id'], unique=False)
    op.create_index(op.f('ix_request_node_id'), 'request', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_node_id'), table_name='request')
    op.drop_index(op.f('ix_request_account_id'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_planrevision_plan_id'), table_name='planrevision')
    op.drop_table('planrevision')
    op.drop_index(op.f('ix_pipelinerun_plan_id'), table_name='pipelinerun')
    op.drop_table('pipelinerun')
    op.drop_index(op.f('ix_edge_board_id'), table_name='edge')
    op.drop_table('edge')
    op.drop_index(op.f('ix_asset_uuid_media_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_node_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_account_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_reference_source_board_id'), table_name='reference')
    op.drop_index(op.f('ix_reference_media_id'), table_name='reference')
    op.drop_table('reference')
    op.drop_index(op.f('ix_plan_board_id'), table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_node_short_id'), table_name='node')
    op.drop_index(op.f('ix_node_board_id'), table_name='node')
    op.drop_index(op.f('ix_node_account_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_chatmessage_board_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_table('boardflowproject')
    op.drop_index(op.f('ix_refreshtoken_token_hash'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_account_id'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    op.drop_index(op.f('ix_devicetoken_token_hash'), table_name='devicetoken')
    op.drop_index(op.f('ix_devicetoken_account_id'), table_name='devicetoken')
    op.drop_table('devicetoken')
    op.drop_index(op.f('ix_board_account_id'), table_name='board')
    op.drop_table('board')
    op.drop_index(op.f('ix_mediaprojectmapping_project_id'), table_name='mediaprojectmapping')
    op.drop_index(op.f('ix_mediaprojectmapping_original_media_id'), table_name='mediaprojectmapping')
    op.drop_table('mediaprojectmapping')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
